"use client";

import { useMemo } from "react";
import { GeoJsonLayer } from "./GeoJsonLayer";
import { NationalAqiLayer } from "./NationalAqiLayer";
import dynamic from "next/dynamic";

const DynamicRoadsLayer = dynamic(() => import("./DynamicRoadsLayer").then(m => ({ default: m.DynamicRoadsLayer })), { ssr: false });
const DynamicPedestrianLayer = dynamic(() => import("./DynamicPedestrianLayer").then(m => ({ default: m.DynamicPedestrianLayer })), { ssr: false });
const DynamicTransitLayer = dynamic(() => import("./DynamicTransitLayer").then(m => ({ default: m.DynamicTransitLayer })), { ssr: false });
import { METRO_COLORS } from "@/lib/constants";
import type { PathOptions } from "leaflet";
import type { Feature } from "geojson";

interface HartiLayersProps {
  activeTab: "bicicleta" | "pejos" | "auto" | "transport" | "aer";
  showDedicate: boolean;
  showMarcate: boolean;
  showRecomandate: boolean;
  showParcuri: boolean;
  showPietonal: boolean;
  showTraversari: boolean;
  visibleLines: string[];
  /** When set, the AQI heatmap clips to this bounding box instead of
   *  rendering Romania-wide. Used on /[judet]/harti so the heatmap only
   *  colors the county. */
  clipBounds?: [[number, number], [number, number]];
  /** Display name of the county we're clipped to — surfaces in the
   *  zoom-out CTA when the user pans/zooms outside the box. */
  countyName?: string;
}

// All bike paths shown as green — no categories, no "recomandate"
function bikePathFilter(feature: Feature): boolean {
  const p = feature.properties ?? {};
  // Only show dedicated cycleways and marked lanes, NOT recommended routes
  return p.highway === "cycleway" || p.cycleway === "track" || p.cycleway === "lane" || p.cycleway === "opposite" || p.bicycle === "designated";
}

const bikeStyle = () =>
  (feature?: Feature): PathOptions => {
    if (!feature) return { weight: 0 };
    if (!bikePathFilter(feature)) return { weight: 0, opacity: 0 };
    return {
      color: "#059669",
      weight: 4,
      opacity: 0.85,
    };
  };

// Metro line styling — colour from OSM tags or fallback to METRO_COLORS
function metroLineStyle(visibleLines: string[]) {
  return (feature?: Feature): PathOptions => {
    if (!feature) return { weight: 0 };
    const ref = (feature.properties?.ref as string) ?? "";
    if (!visibleLines.includes(ref)) return { weight: 0, opacity: 0 };
    const color = (feature.properties?.colour as string) ?? METRO_COLORS[ref] ?? "#64748b";
    return { color, weight: 5, opacity: 0.85 };
  };
}

function metroStationStyle(): PathOptions {
  return {
    radius: 6,
    fillColor: "#ffffff",
    color: "#1e293b",
    weight: 2,
    opacity: 1,
    fillOpacity: 1,
  } as PathOptions;
}

// pedestrianAccessStyle / pedestrianRestrictedStyle removed — the old
// 23 MB pietonal-romania.json + 255 kB pietonal-neaccesibil.json are no
// longer loaded. Footway styling now lives in DynamicPedestrianLayer
// which serves Overpass results on the current viewport.

const parkStyle: PathOptions = {
  color: "#059669",
  weight: 1.5,
  opacity: 0.7,
  fillColor: "#10b981",
  fillOpacity: 0.25,
};

const tramStyle: PathOptions = {
  color: "#EAB308",
  weight: 3,
  opacity: 0.7,
  dashArray: "4 4",
};

// Trolleybus lines come from a national static dataset (~5 MB)
// generated by scripts/fetch-national-geojson.ts trolleybus.
// Purple/violet so the eye separates them from yellow trams and
// orange bus stops at a glance.
const trolleybusStyle: PathOptions = {
  color: "#8B5CF6",
  weight: 2.5,
  opacity: 0.7,
  dashArray: "2 4",
};

function trolleybusPopup(feature: Feature): string {
  const p = feature.properties ?? {};
  const ref = p.ref ?? "";
  const name = p.name ?? "Linie troleibuz";
  const operator = p.operator
    ? `<br/><span style="font-size:10px;color:#94a3b8">${p.operator}</span>`
    : "";
  return `<div style="min-width:160px"><b>${ref ? `Linia ${ref} — ${name}` : name}</b><br/><span style="font-size:11px;color:#64748b">Linie troleibuz</span>${operator}</div>`;
}

function bikePopup(feature: Feature): string {
  const p = feature.properties ?? {};
  const name = p.name ?? "Pistă de bicicletă";
  return `<div style="min-width:180px"><b>${name}</b><br/><span style="font-size:11px;color:#64748b">Pistă ciclism</span></div>`;
}

function metroLinePopup(feature: Feature): string {
  const p = feature.properties ?? {};
  const name = p.name ?? `Linia ${p.ref ?? ""}`;
  return `<div><b>${name}</b><br/><span style="font-size:11px;color:#64748b">${p.operator ?? "Metrorex"}</span></div>`;
}

function metroStationPopup(feature: Feature): string {
  const p = feature.properties ?? {};
  return `<div><b>${p.name ?? "Stație metrou"}</b><br/><span style="font-size:11px;color:#64748b">${p.operator ?? "Metrorex"}</span></div>`;
}

// pedestrianPopup + pedestrianRestrictedPopup moved into
// DynamicPedestrianLayer where the rendering now happens.

function parkPopup(feature: Feature): string {
  const p = feature.properties ?? {};
  return `<div><b>${p.name ?? "Parc"}</b></div>`;
}

export default function HartiLayers(props: HartiLayersProps) {
  const {
    activeTab,
    showDedicate,
    showMarcate,
    showRecomandate,
    showParcuri,
    showPietonal,
    visibleLines,
    clipBounds,
    countyName,
  } = props;

  // Memoize style functions — stable references prevent GeoJSON re-creation on every map pan/zoom
  // show* aren't args la bikeStyle(); sunt totuși deps logice fiindcă schimbarea
  // lor poate trigger-uia un re-render intenționat dacă bikeStyle ajunge să
  // consume props în viitor.
  const memoizedBikeStyle = useMemo(
    () => bikeStyle(),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [showDedicate, showMarcate, showRecomandate]
  );
  const memoizedMetroStyle = useMemo(() => metroLineStyle(visibleLines), [visibleLines]);

  if (activeTab === "bicicleta") {
    return (
      <GeoJsonLayer
        key="bike"
        url="/geojson/bicicleta-romania.json"
        style={memoizedBikeStyle}
        popupFormatter={bikePopup}
      />
    );
  }

  if (activeTab === "pejos") {
    // Parks stay static — 2 MB, covers every leisure=park in RO in one
    // shot. Footways + pedestrian streets are now served by Overpass
    // on the current viewport (DynamicPedestrianLayer) — the old
    // pietonal-romania.json was 23 MB and destroyed mobile first-load.
    return (
      <>
        {showParcuri && (
          <GeoJsonLayer key="parks" url="/geojson/parcuri-romania.json" style={parkStyle} popupFormatter={parkPopup} />
        )}
        {showPietonal && <DynamicPedestrianLayer />}
      </>
    );
  }

  if (activeTab === "auto") {
    return (
      <>
        {/* Static layers: autostrăzi + naționale (always visible, lightweight) */}
        <GeoJsonLayer
          key="autostrazi"
          url="/geojson/autostrazi-romania.json"
          style={() => ({ color: "#DC2626", weight: 3, opacity: 0.9 })}
          popupFormatter={(f: Feature) => {
            const p = f.properties ?? {};
            return `<b>${p.ref || "Autostradă"}</b><br/><span style="font-size:11px;color:#64748b">${p.name || ""}</span>`;
          }}
        />
        <GeoJsonLayer
          key="nationale"
          url="/geojson/nationale-romania.json"
          style={(f?: Feature) => {
            const hw = f?.properties?.highway;
            if (hw === "trunk") return { color: "#F97316", weight: 2, opacity: 0.8 };
            return { color: "#EAB308", weight: 1.5, opacity: 0.7 };
          }}
          popupFormatter={(f: Feature) => {
            const p = f.properties ?? {};
            return `<b>${p.ref || "DN"}</b><br/><span style="font-size:11px;color:#64748b">${p.name || "Drum național"}</span>`;
          }}
        />
        {/* Dynamic: streets load from Overpass API when zoomed in (zoom >= 13) */}
        <DynamicRoadsLayer />
      </>
    );
  }

  if (activeTab === "transport") {
    return (
      <>
        {/* Static: metro lines + stations + national tram + trolleybus
            backbone. Always on, small file sizes, gives the bird's-eye
            view. The dynamic layer below fills in stops + extra rail
            at street zoom. */}
        <GeoJsonLayer key="metro-lines" url="/geojson/metrou.json" style={memoizedMetroStyle} popupFormatter={metroLinePopup} />
        <GeoJsonLayer key="metro-stations" url="/geojson/metrou-statii.json" style={metroStationStyle()} popupFormatter={metroStationPopup} />
        <GeoJsonLayer key="trams" url="/geojson/tramvai-romania.json" style={tramStyle} />
        <GeoJsonLayer
          key="trolleybus"
          url="/geojson/troleibuz-romania.json"
          style={trolleybusStyle}
          popupFormatter={trolleybusPopup}
        />
        {/* Dynamic: bus stops + extra rail progressively stream in
            from Overpass at zoom >= 13. */}
        <DynamicTransitLayer />
      </>
    );
  }

  if (activeTab === "aer") {
    return (
      <NationalAqiLayer
        key={clipBounds ? `aqi-county-${clipBounds[0]?.join(",")}` : "aqi-national"}
        clipBounds={clipBounds}
        countyName={countyName}
      />
    );
  }

  return null;
}
